### ISSUE TITLE
Support for custom widgets

### ISSUE THREAD

**Issue by tilk48** [chgibb/hydro-sdk#37]
Hi,

First of all I must say that I love the project and I think that this will be a major step forward for the entire flutter eco system. Im currently working on a project which would not be possible without a way insert view code at runtime, so thank you very much for making this!

My project has a distinct set of custom widgets which conform to our design specifications and I would have to be able to use them from the hydro code. Is there any way to make this work with the engine?

I was thinking about maybe something like this for the ts side:

`
    public build(): Widget {
        return new CustomWidget<MyWidgetName>({
          <myParameterName>: someValue
       });
    }
`

And then passing a function to the dart widget which receives the widget name and the set of parameters to map to my own widget.

What do you think of this approach?
Id be very willing to help with implementing this but I wanted to hear your opinion first and maybe get a starting point. I have already written another dart widget which makes it possible to load from a ByteData object, Im going to open a merge request for that later.

**Comment by chgibb** [comment]
I appreciate the kind words! 

Internally, there is a system of object boxers/unboxers, builtin namespaces and builtin hooks. I think properly documenting how these things work together, and providing a simple way for consumers of `RunFromNetwork` to add their own would be the best approach. These systems work well together and are already battled tested as they are how everything under `hydro-sdk/runtime/flutter` is implemented.

**Comment by tilk48** [comment]
Having a simple to add own hooks would be perfect!

The lack of this feature is indeed a blocker for me as I need the guest code to be deeper integrated into the host code.

**Comment by chgibb** [comment]
There's a few different patterns for binding Dart objects that have emerged. The simplest way to bind a Dart widget along with an API for custom namespaces has been started:
https://github.com/chgibb/hydro-sdk/blob/custom-widgets/test/widget/customWidget-1_test.dart
https://github.com/chgibb/hydro-sdk/blob/custom-widgets/test/widget/customWidget-1.ts

I still need to add comments for both of those tests as well as some higher level documentation on how to use `customNamespaces` in `RunFromNetwork` and a few other things.

**Comment by tilk48** [comment]
This looks really good, cant wait for this to be ready!

Am I right to assume that this will also work to bind functions?

**Comment by chgibb** [comment]
@tilk48 indeed it will! See the linked PR #42

**Comment by chgibb** [comment]
@tilk48 I think what you're looking for here was satisfied. If not, please feel free to reopen.
